-- Add richer fields to coach_profiles matching player-like depth
ALTER TABLE public.coach_profiles
  ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS coaching_style TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS dominant_hand public.dominant_hand DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS preferred_side TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS volley_pct INTEGER DEFAULT 50,
  ADD COLUMN IF NOT EXISTS forehand_pct INTEGER DEFAULT 50,
  ADD COLUMN IF NOT EXISTS serve_pct INTEGER DEFAULT 50,
  ADD COLUMN IF NOT EXISTS smash_pct INTEGER DEFAULT 50,
  ADD COLUMN IF NOT EXISTS backhand_pct INTEGER DEFAULT 50,
  ADD COLUMN IF NOT EXISTS lob_pct INTEGER DEFAULT 50,
  ADD COLUMN IF NOT EXISTS best_shot TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS weakest_shot TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS playtomic_level NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS playtomic_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS nationality TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS languages TEXT[] DEFAULT '{}'::TEXT[],
  ADD COLUMN IF NOT EXISTS racket_brand TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS racket_model TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS racket_type public.racket_type DEFAULT NULL;

-- Add phone to profiles table so admins can see it for all users
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT NULL;